### ISSUE TITLE
Parquet 구조 작성

### ISSUE THREAD

**Issue by ujeongoh** [FlaschenbookProject/Flashenbook#15]
### Issue 타입 ('x' 로 표기)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [x] 📦 Chore (Release)
- [ ] ⏩ Revert (Rollback)

### 상세 내용
- Data lake에 들어갈 raw 데이터의 Parquet 구조를 작성합니다.

### 예상 소요 시간
- [ ] `0.5h`
- [x] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [ ] `3h`

### 참고사항
- 도서 API 참고하여 구조작성

**Comment by ssongjj** [comment]
https://beaded-sink-0ff.notion.site/ERD-Parquet-d5c5c22114084dfe80a95f6a641bb34b?pvs=4
